# Generated by Django 3.2.6 on 2021-09-04 18:37

import Information.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameAndFamily', models.CharField(max_length=100)),
                ('LabelWork', models.CharField(max_length=50)),
                ('AboutMe', models.TextField()),
                ('UserInstagram', models.CharField(max_length=100)),
                ('UserTelegram', models.CharField(max_length=100)),
                ('UserEmail', models.CharField(max_length=100)),
                ('Skills', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Link', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to=Information.models.UploadSrcImage)),
                ('DateTimeField', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
