# Generated by Django 3.2.6 on 2021-09-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksample',
            name='Descriptions',
            field=models.TextField(default='Txt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksample',
            name='Skills',
            field=models.TextField(default='Text'),
            preserve_default=False,
        ),
    ]
