# Generated by Django 3.2.6 on 2022-03-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0004_auto_20210906_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='UserGithub',
            field=models.CharField(default='FZl47', max_length=100),
            preserve_default=False,
        ),
    ]
